from enum import Enum


class ChannelCodec(str, Enum):
    # Audio (PyAV codecs)
    Aac = "aac"
    AacFixed = "aac_fixed"
    AacLatm = "aac_latm"
    Alac = "alac"
    Flac = "flac"
    LibMp3Lame = "libmp3lame"
    LibOpus = "libopus"
    LibVorbis = "libvorbis"
    Mp3 = "mp3"
    Mp3Adu = "mp3adu"
    Mp3AduFloat = "mp3adufloat"
    Mp3Float = "mp3float"
    Mp3On4 = "mp3on4"
    Mp3On4Float = "mp3on4float"
    Opus = "opus" 
    PcmF32Be = "pcm_f32be" 
    PcmF32Le = "pcm_f32le"
    PcmS16Be = "pcm_s16be" 
    PcmS16BePlanar = "pcm_s16be_planar" 
    PcmS16Le = "pcm_s16le"
    PcmS16LePlanar = "pcm_s16le_planar" 
    PcmS24Be = "pcm_s24be"  
    PcmS24Le = "pcm_s24le"
    PcmS24LePlanar = "pcm_s24le_planar"  
    PcmS32Be = "pcm_s32be"  
    PcmS32Le = "pcm_s32le"
    PcmS32LePlanar = "pcm_s32le_planar"  
    Vorbis = "vorbis"  

    # Image (Pillow modes)
    One = "1"
    Cmyk = "CMYK"
    L = "L"
    P = "P"
    Rgb = "RGB"
    Rgba = "RGBA"
    YCbCr = "YCbCr"

    # Text / Subtitle (PyAV codecs)
    Ass = "ass"
    MovText = "mov_text"
    Srt = "srt"  
    Ssa = "ssa"
    Subrip = "subrip"
    Webvtt = "webvtt"

    # Video (PyAV codecs)
    Av1 = "av1"  
    Av1Cuvid = "av1_cuvid"
    Ffv1 = "ffv1"
    H264 = "h264"  
    H264Cuvid = "h264_cuvid"
    H264V4l2m2m = "h264_v4l2m2m"
    Hevc = "hevc"
    HevcCuvid = "hevc_cuvid"
    HevcV4l2m2m = "hevc_v4l2m2m"
    LibaomAv1 = "libaom-av1"
    LibDav1d = "libdav1d"  
    LibOpenH264 = "libopenh264"  
    Libvpx = "libvpx"
    LibvpxVp9 = "libvpx-vp9"
    Libx264 = "libx264"
    Libx265 = "libx265"
    Mjpeg = "mjpeg"
    MjpegB = "mjpegb"  
    MjpegCuvid = "mjpeg_cuvid"
    Prores = "prores"  
    ProresAw = "prores_aw"  
    ProresKs = "prores_ks"
    ProresRaw = "prores_raw"  
    Theora = "theora"  
    Vp8 = "vp8"  
    Vp8Cuvid = "vp8_cuvid"
    Vp8V4l2m2m = "vp8_v4l2m2m"
    Vp9 = "vp9"  
    Vp9Cuvid = "vp9_cuvid"
    Vp9V4l2m2m = "vp9_v4l2m2m"
