from datetime import datetime, timezone

from pydantic import Field

from norman_objects.norman_base_model import NormanBaseModel
from norman_objects.shared.date.normalized_datetime import NormalizedDateTime
from norman_objects.shared.invocation_signatures.invocation_signature import InvocationSignature


class Invocation(NormanBaseModel):
    """
    Represents a single model invocation event, including metadata,
    timestamps, and all associated input/output signatures.

    An `Invocation` acts as the root record for a single execution of a
    model. It contains identifying information, creation time, and the
    full collection of structured inputs and outputs used for or
    produced by the invocation.

    **Fields**

    - **id** (`str`)
      Unique identifier for the invocation. Defaults to "0".

    - **account_id** (`str`)
      Identifier of the account that triggered the invocation.

    - **model_id** (`str`)
      Identifier of the model executed during this invocation.

    - **creation_time** (`datetime`)
      Timestamp (UTC) indicating when the invocation was created.
      Defaults to the current time via `datetime.now(timezone.utc)`.

    - **inputs** (`list[InvocationSignature]`)
      List of input signatures supplied to the invocation.
      Each element is an `InvocationSignature` instance.

    - **outputs** (`list[InvocationSignature]`)
      List of output signatures generated by the invocation.
      Each element is an `InvocationSignature` instance.
    """
    id: str = "0"
    account_id: str
    model_id: str
    creation_time: NormalizedDateTime = Field(default_factory=lambda: datetime.now(timezone.utc))

    inputs: list[InvocationSignature] = []
    outputs: list[InvocationSignature] = []

