from datetime import datetime, timezone
from typing import Optional

from pydantic import Field

from norman_objects.norman_base_model import NormanBaseModel
from norman_objects.shared.date.normalized_datetime import NormalizedDateTime
from norman_objects.shared.notifications.severity import Severity


class Notification(NormanBaseModel):
    """
    Represents a user-facing notification generated by the system,
    including informational updates, warnings, success messages,
    and error alerts.

    Notifications are tied to an account and may optionally reference a
    specific model or entity. Each notification includes metadata such as
    creation time, severity level, read status, and free-form message text.

    **Fields**

    - **id** (`str`)
      Unique identifier for the notification.

    - **account_id** (`str`)
      Identifier of the account to which this notification belongs.

    - **entity_id** (`str`)
      Identifier associated with the event or resource that triggered
      the notification.

    - **creation_time** (`datetime`)
      Timestamp (UTC) when the notification was created.
      Defaults to the current time.

    - **model_name** (`Optional[str]`)
      Optional model name associated with the event, when relevant.

    - **title** (`str`)
      Short human-readable title summarizing the notification.

    - **message** (`str`)
      Full descriptive text explaining the notification.

    - **read_status** (`int`)
      Numeric flag indicating whether the notification has been read.
      Typical values:
          - `0` - Unread
          - `1` - Read

    - **severity** (`Severity`)
      Classification of the notification level:
          - Error
          - Info
          - Success
          - Warning
    """
    id: str
    account_id: str
    entity_id: str
    creation_time: NormalizedDateTime = Field(default_factory=lambda: datetime.now(timezone.utc))
    model_name: Optional[str] = None
    title: str
    message: str
    read_status: int
    severity: Severity

